### ISSUE TITLE
Consider adding option to show failed only tests in output.

### ISSUE THREAD

**Issue by igor-korotenko** [radarsh/gradle-test-logger-plugin#38]
Would be great to have an option to show only failed tests in CI(Jenkins) build output. We have pretty big amount of tests and Jenkins output overflows several times, while at the same time in case if build failed on CI passed tests are not necessary things there. Smth. like
```groovy
testLogger {
    showOnlyFailedInPlainOutputMode true
}
```
This will work only for `--console=plain` option enabled. 
Also maybe legit if this flag is enabled by default for `--console=plain`

**Comment by radarsh** [comment]
That's a great suggestion. However, themes are purely for appearance sake and shouldn't affect the behaviour of the test logger. Besides not everyone uses plain console on Jenkins, [thanks to plugins that support ANSI colours on Jenkins](https://github.com/jenkinsci/ansicolor-plugin).

So I am thinking of exposing a configuration option called `showOnlyFailed true`. I appreciate there would still be a desire to use a configuration that's different on dev machines compared to Jenkins. In order to facilitate that, I am pondering the idea of allowing test logger configuration by using System properties. Once that's implemented, we can change the configuration at runtime.

**Comment by igor-korotenko** [comment]
Sounds great! Thank you.
